#!/usr/bin/env python3
"""Inspect one slide's feature files (.pt/.npy) by slide id.

Example:
    python MsaMIL_Net/tools/inspect_slide_features.py \
        --slide 2460239-B2 \
        --feature-dir /private/ljh-data/shared/MsaMIL/MsaMIL_Net/data/features_phikon_Yi
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import numpy as np
import torch


def _print_numpy(name: str, path: Path, max_items: int, full: bool) -> None:
    arr = np.load(path)
    print(f"\n[{name}] {path}")
    print(f"  shape: {arr.shape}")
    print(f"  dtype: {arr.dtype}")

    if full:
        print("  content:")
        print(arr)
        return

    flat = arr.reshape(-1)
    n = min(max_items, flat.size)
    print(f"  preview first {n} values:")
    print(flat[:n])
    if flat.size > n:
        print(f"  ... ({flat.size - n} more values not shown, use --full to print all)")


def _print_obj(name: str, obj: Any, max_items: int, full: bool, indent: str = "  ") -> None:
    if isinstance(obj, torch.Tensor):
        print(f"{indent}type: torch.Tensor")
        print(f"{indent}shape: {tuple(obj.shape)}")
        print(f"{indent}dtype: {obj.dtype}")
        if full:
            print(f"{indent}content:")
            print(obj)
        else:
            flat = obj.reshape(-1)
            n = min(max_items, flat.numel())
            print(f"{indent}preview first {n} values:")
            print(flat[:n])
            if flat.numel() > n:
                print(f"{indent}... ({flat.numel() - n} more values not shown, use --full to print all)")
        return

    if isinstance(obj, np.ndarray):
        print(f"{indent}type: numpy.ndarray")
        print(f"{indent}shape: {obj.shape}")
        print(f"{indent}dtype: {obj.dtype}")
        if full:
            print(f"{indent}content:")
            print(obj)
        else:
            flat = obj.reshape(-1)
            n = min(max_items, flat.size)
            print(f"{indent}preview first {n} values:")
            print(flat[:n])
            if flat.size > n:
                print(f"{indent}... ({flat.size - n} more values not shown, use --full to print all)")
        return

    if isinstance(obj, dict):
        print(f"{indent}type: dict")
        print(f"{indent}keys: {list(obj.keys())}")
        for k, v in obj.items():
            print(f"{indent}- key: {k}")
            _print_obj(name=f"{name}.{k}", obj=v, max_items=max_items, full=full, indent=indent + "  ")
        return

    if isinstance(obj, (list, tuple)):
        print(f"{indent}type: {type(obj).__name__}")
        print(f"{indent}len: {len(obj)}")
        show_n = len(obj) if full else min(max_items, len(obj))
        for i in range(show_n):
            print(f"{indent}- idx: {i}")
            _print_obj(name=f"{name}[{i}]", obj=obj[i], max_items=max_items, full=full, indent=indent + "  ")
        if not full and len(obj) > show_n:
            print(f"{indent}... ({len(obj) - show_n} more items not shown, use --full to print all)")
        return

    print(f"{indent}type: {type(obj).__name__}")
    print(f"{indent}value: {obj}")


def _print_pt(path: Path, max_items: int, full: bool) -> None:
    # The file is generated by this project, so normal torch.load is expected.
    obj = torch.load(path, map_location="cpu")
    print(f"\n[features] {path}")
    _print_obj(name="features", obj=obj, max_items=max_items, full=full)


def main() -> None:
    parser = argparse.ArgumentParser(description="Inspect one slide's .pt/.coords/.scales files")
    parser.add_argument("--slide", required=True, help="Slide id, e.g. 2460239-B2")
    parser.add_argument("--feature-dir", required=True, type=Path, help="Directory containing feature files")
    parser.add_argument("--max-items", type=int, default=20, help="Preview item count when not using --full")
    parser.add_argument("--full", action="store_true", help="Print full content of each file")
    args = parser.parse_args()

    feature_dir = args.feature_dir.expanduser().resolve()
    if not feature_dir.exists() or not feature_dir.is_dir():
        raise FileNotFoundError(f"feature-dir not found or not a directory: {feature_dir}")

    coords_path = feature_dir / f"{args.slide}_coords.npy"
    scales_path = feature_dir / f"{args.slide}_scales.npy"
    pt_path = feature_dir / f"{args.slide}.pt"

    print("Input summary:")
    print(f"  slide: {args.slide}")
    print(f"  feature_dir: {feature_dir}")

    missing = [p for p in [coords_path, scales_path, pt_path] if not p.exists()]
    if missing:
        print("\nMissing files:")
        for p in missing:
            print(f"  - {p}")
        raise FileNotFoundError("Some required files are missing")

    print(f"\nResolved files:\n  - {coords_path}\n  - {scales_path}\n  - {pt_path}")

    _print_numpy("coords", coords_path, max_items=args.max_items, full=args.full)
    _print_numpy("scales", scales_path, max_items=args.max_items, full=args.full)
    _print_pt(pt_path, max_items=args.max_items, full=args.full)


if __name__ == "__main__":
    main()
